Fix ValidateCryptRsa2( ) function fail when running Cryptest.efi
tianocore/edk2-staging pull request #301
Opened 2022-08-16 05:34 UTC by Zhiqiang520

Signed-off-by: Zhao, Zhiqiang <zhiqiang.zhao@intel.com>

2022-08-17 05:28 UTC, qizhangz approved these changes
looks good to me

2022-08-18 01:27 UTC, liuw1 requested changes

2022-08-18 01:27 UTC, liuw1 commented on DeviceSecurityPkg/Test/Cryptest/RsaVerify2.c
> +    0x30, 0x82, 0x04, 0x96, 0x30, 0x82, 0x02, 0x7E, 0xA0, 0x03, 0x02, 0x01,
Please keep 16 bytes in one line.

2022-08-18 13:56 UTC, Zhiqiang520 commented on DeviceSecurityPkg/Test/Cryptest/RsaVerify2.c
> +    0x30, 0x82, 0x04, 0x96, 0x30, 0x82, 0x02, 0x7E, 0xA0, 0x03, 0x02, 0x01,
I have updated.

2022-08-18 13:58 UTC, liuw1 approved these changes

2022-08-18 13:58 UTC, liuw1 approved these changes

2022-08-26 01:49 UTC, merged