Fix ValidateCryptRsa( ) function fail when running Cryptest.efi
tianocore/edk2-staging pull request #303
Opened 2022-08-17 04:20 UTC by Zhiqiang520

Signed-off-by: Zhao, Zhiqiang <zhiqiang.zhao@intel.com>

2022-08-17 05:08 UTC, qizhangz approved these changes
looks like good to me

2022-08-18 01:25 UTC, liuw1 requested changes

2022-08-18 01:25 UTC, liuw1 commented on DeviceSecurityPkg/Test/Cryptest/RsaVerify.c
> +  0x8f, 0x8f, 0x38, 0x63, 0x19, 0x01, 0x69, 0xa4, 0xfa, 0xd3, 0x57, 0x90,
It's better to have 16 bytes in one line.

2022-08-18 13:58 UTC, Zhiqiang520 commented on DeviceSecurityPkg/Test/Cryptest/RsaVerify.c
> +  0x8f, 0x8f, 0x38, 0x63, 0x19, 0x01, 0x69, 0xa4, 0xfa, 0xd3, 0x57, 0x90,
I have updated.

2022-08-24 05:37 UTC, qizhangz approved these changes

2022-08-24 06:11 UTC, liuw1 approved these changes

2022-08-26 01:50 UTC, merged